### ISSUE TITLE
Everyplay crash on Samsung Ace/Zte/Tabs 

### ISSUE THREAD

**Issue by ZenithCode** [Everyplay/everyplay-unity-sdk#7] opened 2015-05-14 08:36 UTC
I'm getting a crash with Everyplay on the devices listed above.  Works fine on most other Androids.

Can you help me with this?

Stacktrace:
05-13 17:19:29.795: I/DEBUG(3014): Build fingerprint: 'samsung/heat3gtfnvzw/heat3gtfnvzw:4.3/JLS36C/S765CUDUANC1:user/release-keys'
05-13 17:19:29.795: I/DEBUG(3014): Revision: '5'
05-13 17:19:29.795: I/DEBUG(3014): pid: 20651, tid: 20670, name: main  >>> com.companyName.titleName <<<
05-13 17:19:29.795: I/DEBUG(3014): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 9801d103
05-13 17:19:30.035: I/DEBUG(3014):     r0 00000001  r1 00000000  r2 00000000  r3 ffffffbc
05-13 17:19:30.035: I/DEBUG(3014):     r4 00000000  r5 00000001  r6 00000000  r7 00000000
05-13 17:19:30.035: I/DEBUG(3014):     r8 40537dca  r9 9801d103  sl 00000000  fp 00000000
05-13 17:19:30.035: I/DEBUG(3014):     ip 00000001  sp 5fe9b9e0  lr 63512923  pc 40537dd0  cpsr 20000030
05-13 17:19:30.035: I/DEBUG(3014):     d0  0000000000000000  d1  0000000000000000
05-13 17:19:30.035: I/DEBUG(3014):     d2  0000000000000000  d3  0000000000000000
05-13 17:19:30.035: I/DEBUG(3014):     d4  070020400f000008  d5  00c801e0ffff0400
05-13 17:19:30.035: I/DEBUG(3014):     d6  0000000000000000  d7  3c0000ff00000000
05-13 17:19:30.035: I/DEBUG(3014):     d8  0000000000000000  d9  0000000000000000
05-13 17:19:30.035: I/DEBUG(3014):     d10 0000000000000000  d11 0000000000000000
05-13 17:19:30.035: I/DEBUG(3014):     d12 0000000000000000  d13 0000000000000000
05-13 17:19:30.035: I/DEBUG(3014):     d14 0000000000000000  d15 0000000000000000
05-13 17:19:30.035: I/DEBUG(3014):     d16 0000000000000000  d17 0000000000000000
05-13 17:19:30.035: I/DEBUG(3014):     d18 0000000000000000  d19 0000000000000000
05-13 17:19:30.035: I/DEBUG(3014):     d20 0000000000000000  d21 0000000000000000
05-13 17:19:30.035: I/DEBUG(3014):     d22 0000000000000000  d23 0000000000000000
05-13 17:19:30.035: I/DEBUG(3014):     d24 000000003f19999a  d25 0000000000000000
05-13 17:19:30.035: I/DEBUG(3014):     d26 3f80000000000000  d27 0000000000000000
05-13 17:19:30.035: I/DEBUG(3014):     d28 0000000000000000  d29 000000003dcccccd
05-13 17:19:30.035: I/DEBUG(3014):     d30 0000000000000000  d31 3f80000000000000
05-13 17:19:30.035: I/DEBUG(3014):     scr 20000012
05-13 17:19:30.035: I/DEBUG(3014): backtrace:
05-13 17:19:30.035: I/DEBUG(3014):     #00  pc 00001dd0  /system/lib/libEGL.so
05-13 17:19:30.035: I/DEBUG(3014):     #01  pc 00009921  /data/app-lib/com.companyName.titleName-1/libeveryplay.so
05-13 17:19:30.035: I/DEBUG(3014):     #02  pc 00010ffc  <unknown>
05-13 17:19:30.035: I/DEBUG(3014): stack:
05-13 17:19:30.035: I/DEBUG(3014):          5fe9b9a0  60e72000  /dev/kgsl-3d0

**Comment by HenryStrattonFW** [comment] 2015-05-21 09:49
We are seeing a similar issue (I think) on most of the devices we have available to test on everyplay seems okay (albeit slow on some devices that have now been disabled) but for some reason on a Galaxy Note 4 initializing everyplay seems to cause the game to crash. the log can be seen here. http://pastebin.com/ZPrhVbYa

Looks like the same, or similar problem, after an everyplay.so call it goes through to some graphics libraries and then the app dies horribly, Its not even when we try to record everyplay, its just if we initialize it, removing that initialization makes it fine again. 

Hope the extra crash log might help someone work out whats going on.

**Comment by surathchatterji** [comment] 2015-05-21 16:46
There is a known issue on devices with Adreno GPU which is currently under investigation. We will release the fix as soon as we are ready. Please consider Blacklisting the devices in question from your dashboard (4th tab) in the meanwhile.

**Comment by aet** [comment] 2015-06-03 04:01
Sorry for the delay, it took some time to get a proper version of Galaxy Note 4 to our test rig
Galaxy Note 4 support is now fixed with 1970-1350 release

Additionally, we've added a new failsafe mode handling, so if we suspect that a crash was
caused by us during the early initialization of the app, we're disabling the recording support

**Closed by aet** 2015-06-03 04:01 UTC
