### ISSUE TITLE
Unity error in Android build

### ISSUE THREAD

**Issue by developer-celmar** [Everyplay/everyplay-unity-sdk#21] opened 2016-12-08 10:41 UTC
ENV
Unity 5.5
OSX

Version control = Hidden Meta files

Attached is the screenshot
![screen shot 2016-12-08 at 6 28 56 pm](https://cloud.githubusercontent.com/assets/6347476/21006897/d1a9172a-bd75-11e6-87c0-775e743e98b2.png)

Your help is highly appreciated.

Regards,
Celmar

**Comment by JustinFincher** [comment] 2017-01-22 05:43
I got the same error, and I removed the `maxSdkVersion` attribute in AndroidManifest.xml. Hope this helps.

**Comment by ullatussimo** [comment] 2017-01-23 09:56
Hello,

Yep, the merging failure is indeed caused by the maxSdkVersion attribute in our AndroidManifest.xml.

We only require the WRITE_EXTERNAL_STORAGE permission until Android API level 18, so we added the attribute to our AndroidManifest in order to bring down the amount of permissions requested on newer systems. This can unfortunately cause conflicts if some other plugin uses the same permission but does not have the maxSdkVersion -attribute set.

In order to make the game build in such a case, the fix is indeed to remove the maxSdkVersion -attribute from the AndroidManifest.xml provided by us.

Hope this helps.

Cheers,
Simo

**Comment by developer-celmar** [comment] 2017-01-24 06:30
Hello,

I tried to build on another machine and it works. Still probing the cause.

Thanks,
Celmar

**Comment by sooperpop** [comment] 2017-02-18 10:27
Hello,

As @ullatussimo suggested, I removed maxSdkVersion from everyplay's manifest. But still getting the same error. Is there anything I am missing out?

Please help.

Thanks,
Sooperpop

**Comment by ullatussimo** [comment] 2017-05-29 10:15
Hello @sooperpop,

Thanks for your response.

Is the error message you are getting exactly the same error?
Can you post a screenshot of the error you are seeing? 
Which other AndroidManifest.xml -files do you have in the project apart from ours?

Cheers,
Simo

**Comment by paugit** [comment] 2017-11-22 06:31
Closing since no activity for over 5 months.

**Closed by paugit** 2017-11-22 06:31 UTC
